# Generated by Django 3.1.14 on 2022-09-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='ZLNumber',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='manufacture_date',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='manufacture_number',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='material',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='revision',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='stencil_number',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='thickness',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
